name: la-dict
version: 0.1.0.0
github: "lumiknit/la-dict"
author: "lumiknit"
maintainer: "aasr4r4@gmail.com"
copyright: "2018 lumikni"

dependencies:
- base >= 4.7 && < 5
- process

library:
  source-dirs: src

executables:
  la-dict-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - la-dict
